/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the recipes
     * @description Return the full collection of recipes.
     */
    get: operations["list_recipes_recipes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Pill
     * @description A tag classifying a recipe.
     */
    Pill: {
      /**
       * Color
       * @enum {string}
       */
      color:
        | "green"
        | "blue"
        | "yellow"
        | "orange"
        | "red"
        | "amber"
        | "pink"
        | "lime"
        | "sky"
        | "rose";
      /** Name */
      name: string;
    };
    /**
     * Recipe
     * @description A cooking recipe.
     */
    Recipe: {
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Imageurl */
      imageUrl: string;
      /** Name */
      name: string;
      /** Pills */
      pills: components["schemas"]["Pill"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_recipes_recipes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Recipe"][];
        };
      };
    };
  };
}
