"""The metadata every table is declared in.

Migrations are autogenerated by comparing it with the database, so a table
that is not registered here is invisible to them. The naming convention gives
every constraint and index a predictable name, which a later migration needs
in order to alter or drop it; it must be in place before the first table.
"""

from sqlalchemy import MetaData

metadata = MetaData(
    naming_convention={
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
)
